### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by KarstensLab** [statdivlab/tinyvamp#5]
I am looking forward to use this package, however I am running into some installation trouble. My error seems to be that I need to install packages ‘logsum’, ‘fastnnls’, but I am not able to easily find these packages in CRAN. Can you share the package installation info for these packages?

**Comment by adw96** [comment]
Thanks for your interest, @KarstensLab ! Yes, you can install them as 

```
remotes::install_github("ailurophilia/logsum")
remotes::install_github("ailurophilia/fastnnls")
```

or equivalently with `devtools::install_github`. 

I'm just working on the vignettes with some of your data, so thank you again for sharing it!

@ailurophilia - do you want the StatDivLab to take over maintenance of those packages? Or are they pretty stable?

**Comment by adw96** [comment]
@KarstensLab If there's a vignette/example you want me to prioritise, let me know and I can wrap it up ASAP. Otherwise, I'll work through them in my current order 😸

**Comment by lakarstens** [comment]
Hi @adw96 - Thanks for your prompt response, it really helped us get up and running with tinyvamp! We're interested in testing the application of tinyvamp to a few projects with low microbial biomass samples. Do you have an ETA for the vingette that uses the karstens et al data?

**Comment by adw96** [comment]
Great to hear it! I'll get something started today and try to have it wrapped up by the end of the week! 🤞

**Comment by adw96** [comment]
In the meantime, the script we used for our analysis is available [here](https://github.com/statdivlab/tinyvamp_supplementary/blob/main/karstens_cv.R), so even if it's not elaborated on/well-explained you have something to go off while you wait for more details 😸

**Comment by adw96** [comment]
I might close this issue for now -- for further updates on the Karstens et al vignette, see #1. Feel free to reopen if you have any more installation issues!
