### ISSUE TITLE
fastnnl and logsum issues

### ISSUE THREAD

**Issue by skeffington** [statdivlab/tinyvamp#7]
Hi,

I love the preprint! Couldn't resist having a play - so tried to install. Unfortunately I couldn't work out where I should be getting packages fastnnls and logsum from. Can you point me in the right direction? I realise it's all underdevelopment, so happy to be patient if I'm jumping the boat!

Best wishes,
Alastair

```
ERROR: dependencies 'fastnnls', 'logsum' are not available for package 'tinyvamp'
```

**Comment by ailurophilia** [comment]
Hi Alastair,

Glad to hear you enjoyed the preprint! Both of those packages are hosted on my personal github, so you should be able to install them with `remotes::install_github("https://github.com/ailurophilia/fastnnls")` and `remotes::install_github("https://github.com/ailurophilia/logsum")` – let me know if this gives you any trouble!

Best,
David

**Comment by skeffington** [comment]
Thanks, that worked!
